FROM scratch
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG TARGETVARIANT=
VOLUME /app/data
COPY dist/cacao-${TARGETOS}-${TARGETARCH}${TARGETVARIANT} /usr/bin/cacao
ENTRYPOINT ["/usr/bin/cacao"]
CMD ["--storage=/app/data"]
